/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head'; 
import { NotificationProvider } from '@/frontend/context/NotificationContext';

import { NotificationList } from '@/frontend/components/Notification/NotificationList'
import { TopBar } from '@/frontend/components/TopBar/TopBar';

import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      
        <body>
          <NotificationProvider>
            <TopBar title="Hub Administrativo" logo="/main/Flashback.png"></TopBar>
            <NotificationList/>
            {children}
          </NotificationProvider>
        </body>
    </html>
  )
}
